# Dependencies
markdown:	kramdown
highlighter: pygments
plugins: [jekyll-paginate]

# Permalinks
permalink: /portfolio/:year/:month/:day/:title

# Setup
title:		Summer Smith
tagline:	'portfolio'
description:	'The portfolio of Summer Smith'
url:		http://summasmiff.github.io

author:
  name:	'Summer Smith'
  url:	http://summasmiff.github.io

paginate:	20

# Custom vars
icon: /assets/images/icon.gif
cover: /assets/images/cover.gif
version:	1.0.1
copyright: <p class="copyright">&copy;2026, <a href="http://summasmiff.github.io" target="_blank">Summer Smith</a>. <a href="http://creativecommons.org/licenses/by-nc/2.5/br/" target="_blank">Some rights reserved</a>.</p>
